# Generated by Django 5.1.1 on 2024-10-11 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insight',
            name='pestle',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='insight',
            name='region',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='insight',
            name='sector',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='insight',
            name='topic',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
