# Generated by Django 5.1.1 on 2024-10-11 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0003_alter_insight_intensity_alter_insight_likelihood_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insight',
            name='impact',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='insight',
            name='url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
