# Generated by Django 5.1.1 on 2024-10-11 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0005_alter_insight_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insight',
            name='published',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='insight',
            name='source',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
